export { ReactComponent as AddToListIcon } from './addToListIcon.svg'
export { ReactComponent as AllowAccessFilesIcon } from './allowAccessFiles.svg'
export { ATMsIcon } from './ATMsIcon'
export { ReactComponent as AttentionIcon } from './attentionIcon.svg'
export * from './BankBranchPageSvg'
export { ReactComponent as SearchIcon } from './BankBranchPageSvg/SearchBar/searchIcon.svg'
export { ReactComponent as CaptionInfo } from './CaptionInfo.svg'
export { ReactComponent as Cards } from './Cards.svg'
export { ReactComponent as MasterCard } from './cards/MasterCard.svg'
export { ReactComponent as Mir } from './cards/Mir.svg'
export { ReactComponent as Visa } from './cards/Visa.svg'
export { ReactComponent as Email } from './CardStatementModalSvg/E-mail.svg'
export { ReactComponent as Facebook } from './CardStatementModalSvg/Facebook.svg'
export { ReactComponent as Instagram } from './CardStatementModalSvg/Instagram.svg'
export { ReactComponent as LinkedIn } from './CardStatementModalSvg/Linkedin.svg'
export { ReactComponent as Skype } from './CardStatementModalSvg/Skype.svg'
export { ReactComponent as Telegram } from './CardStatementModalSvg/Telegram.svg'
export { ReactComponent as Twitter } from './CardStatementModalSvg/Twitter.svg'
export { ReactComponent as WhatsApp } from './CardStatementModalSvg/WhatsApp.svg'
export { ReactComponent as Close } from './Close.svg'
export { ReactComponent as CloseBtn } from './CloseBtn.svg'
export { ContactsIcon } from './ContactsIcon'
export * from './contactsPageSvg'
export { CurrencyIcon } from './CurrencyIcon'
export { ReactComponent as Done } from './Done.svg'
export { ReactComponent as DownloadIcon } from './downloadIcon.svg'
export { ReactComponent as ErrorAlert } from './errorAlert.svg'
export { ReactComponent as errorNotification } from './errorNotification.svg'
export * from './ExchangeRatesPageSvg'
export { ReactComponent as FooterPhone } from './FooterPhone.svg'
export * from './HelpSvg'
export { ReactComponent as IconDelete } from './iconDelete.svg'
export { ReactComponent as BankServiceIcon } from './iconFinancialServices.svg'
export { ReactComponent as Info } from './info.svg'
export { ReactComponent as Logout } from './Logout.svg'
export * from './MainPageScroll'
export { ReactComponent as NextArrow } from './nextArrow.svg'
export { ReactComponent as Pencil } from './Pencil.svg'
export { ReactComponent as BankingServicesIcon } from './PopularPayments/BankingServicesIcon.svg'
export { ReactComponent as InternetIcon } from './PopularPayments/InternetIcon.svg'
export { ReactComponent as MobileIcon } from './PopularPayments/MobileIcon.svg'
export { ReactComponent as OtherIcon } from './PopularPayments/OtherIcon.svg'
export { ReactComponent as SberIcon } from './PopularPayments/SberIcon.svg'
export { ReactComponent as TransferEasyIcon } from './PopularPayments/TransferEasyIcon.svg'
export { ReactComponent as TransferIcon } from './PopularPayments/TransferIcon.svg'
export { ReactComponent as UtilitiesIcon } from './PopularPayments/UtilitiesIcon.svg'
export { ReactComponent as PrevArrow } from './prevArrow.svg'
export { ReactComponent as SelectArrowDown } from './SelectArrowDown.svg'
export { ReactComponent as SelectOptionSuccess } from './SelectOptionSuccess.svg'
export { ReactComponent as Preloader } from './Spinner.svg'
export { ReactComponent as SuccessIcon } from './successIcon.svg'
export { ReactComponent as TextLinkIcon } from './textPdfIcon.svg'
export { ReactComponent as TryAgainIcon } from './tryAgainIcon.svg'
export { ReactComponent as VisibilityOff } from './VisibilityOff.svg'
export { ReactComponent as VisibilityOn } from './VisibilityOn.svg'
